name: ReplaceCraft
version: 1.3.4
main: net.kunmc.lab.replacecraft.ReplaceCraftPlugin
api-version: 1.16
author: stcYps
website: https://github.com/TeamKun/ReplaceCraft
commands:
  replace:
    description: ReplaceCraftPlugin Main Command
    usage: /replace <引数>
    permission: op